# -*- coding: utf-8 -*-
"""review_analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYRJlaq5fVX0WhoOWnVVT79Dw7ROns4a
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile review_analyzer.py
# 
# import os
# import json
# import requests
# 
# 
# MODEL_NAME = "gemini-2.5-flash"
# 
# API_URL = (
#     f"https://generativelanguage.googleapis.com/v1beta/"
#     f"models/{MODEL_NAME}:generateContent"
# )
# 
# 
# PROMPT_TEMPLATE = """
# You are a retail customer-feedback analyst for ChicStyle.
# 
# Analyze the customer review and return only valid JSON.
# 
# Return these fields:
# 
# Category
# Sentiment
# Urgency
# Summary
# Personalized_Message
# Retail_Insight
# 
# Sentiment must be:
# Positive, Negative, Neutral, or Mixed.
# 
# Urgency must be:
# High, Medium, or Low.
# 
# Customer review:
# {review}
# """
# 
# 
# RESPONSE_SCHEMA = {
#     "type": "OBJECT",
#     "properties": {
#         "Category": {
#             "type": "STRING"
#         },
#         "Sentiment": {
#             "type": "STRING",
#             "enum": [
#                 "Positive",
#                 "Negative",
#                 "Neutral",
#                 "Mixed"
#             ]
#         },
#         "Urgency": {
#             "type": "STRING",
#             "enum": [
#                 "High",
#                 "Medium",
#                 "Low"
#             ]
#         },
#         "Summary": {
#             "type": "STRING"
#         },
#         "Personalized_Message": {
#             "type": "STRING"
#         },
#         "Retail_Insight": {
#             "type": "STRING"
#         }
#     },
#     "required": [
#         "Category",
#         "Sentiment",
#         "Urgency",
#         "Summary",
#         "Personalized_Message",
#         "Retail_Insight"
#     ]
# }
# 
# 
# def analyze_review(review_text, api_key=None):
#     """
#     Send one review to Gemini and return a Python dictionary.
#     """
# 
#     if not review_text or not review_text.strip():
#         raise ValueError("Please enter a customer review.")
# 
#     # First use the key passed by app.py.
#     # Otherwise, look for an environment variable.
#     key = api_key or os.getenv("GEMINI_API_KEY")
# 
#     if not key:
#         raise ValueError(
#             "Gemini API key is missing."
#         )
# 
#     prompt = PROMPT_TEMPLATE.format(
#         review=review_text.strip()
#     )
# 
#     payload = {
#         "contents": [
#             {
#                 "role": "user",
#                 "parts": [
#                     {
#                         "text": prompt
#                     }
#                 ]
#             }
#         ],
#         "generationConfig": {
#             "temperature": 0.1,
#             "responseMimeType": "application/json",
#             "responseSchema": RESPONSE_SCHEMA
#         }
#     }
# 
#     response = requests.post(
#         API_URL,
#         params={
#             "key": key
#         },
#         headers={
#             "Content-Type": "application/json"
#         },
#         json=payload,
#         timeout=90
#     )
# 
#     response.raise_for_status()
# 
#     raw_response = response.json()
# 
#     try:
#         response_text = (
#             raw_response["candidates"][0]
#             ["content"]["parts"][0]["text"]
#         )
# 
#         result = json.loads(response_text)
# 
#     except (
#         KeyError,
#         IndexError,
#         json.JSONDecodeError
#     ) as error:
# 
#         raise ValueError(
#             f"Could not parse Gemini response: {raw_response}"
#         ) from error
# 
#     return result

MODEL_NAME = "gemini-2.5-flash"

PROMPT_TEMPLATE = """
You are a retail customer-feedback analyst...
"""

def analyze_review(review_text, api_key=None):
    """
    Send one review to Gemini and return a Python dictionary.
    """

    if not review_text or not review_text.strip():
        raise ValueError("Please enter a customer review.")

    # First use the key passed by app.py.
    # Otherwise, look for an environment variable.
    key = api_key or os.getenv("GEMINI_API_KEY")

    if not key:
        raise ValueError(
            "Gemini API key is missing."
        )

    prompt = PROMPT_TEMPLATE.format(
        review=review_text.strip()
    )

    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [
                    {
                        "text": prompt
                    }
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.1,
            "responseMimeType": "application/json",
            "responseSchema": RESPONSE_SCHEMA
        }
    }

    response = requests.post(
        API_URL,
        params={
            "key": key
        },
        headers={
            "Content-Type": "application/json"
        },
        json=payload,
        timeout=90
    )

    response.raise_for_status()

    raw_response = response.json()

    try:
        response_text = (
            raw_response["candidates"][0]
            ["content"]["parts"][0]["text"]
        )

        result = json.loads(response_text)

    except (
        KeyError,
        IndexError,
        json.JSONDecodeError
    ) as error:

        raise ValueError(
            f"Could not parse Gemini response: {raw_response}"
        ) from error

    return result

import os

print(os.listdir())

!cat review_analyzer.py

from review_analyzer import analyze_review

from google.colab import userdata

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

test_result = analyze_review(
    "Terrible fabric. I loved the shirt until I washed it!",
    api_key=GEMINI_API_KEY
)

print(test_result)

import gradio as gr
from review_analyzer import analyze_review
from google.colab import userdata

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

def gradio_analyze_review(review_text):
    try:
        result = analyze_review(
            review_text,
            api_key=GEMINI_API_KEY
        )

        return (
            result.get("Category", ""),
            result.get("Sentiment", ""),
            result.get("Urgency", ""),
            result.get("Summary", ""),
            result.get("Personalized_Message", ""),
            result.get("Retail_Insight", "")
        )

    except Exception as error:
        return (
            "Error",
            "Error",
            "Error",
            f"{type(error).__name__}: {error}",
            "",
            ""
        )

with gr.Blocks(
    title="ChicStyle Retail Feedback Intelligence"
) as demo:

    gr.Markdown(
        "# ChicStyle Retail Feedback Intelligence"
    )

    with gr.Row():

        with gr.Column():
            review_input = gr.Textbox(
                label="Customer Review",
                lines=8
            )

            submit_button = gr.Button(
                "Submit",
                variant="primary"
            )

            clear_button = gr.Button("Clear")

        with gr.Column():
            category_output = gr.Textbox(
                label="Category"
            )

            sentiment_output = gr.Textbox(
                label="Sentiment"
            )

            urgency_output = gr.Textbox(
                label="Urgency"
            )

            summary_output = gr.Textbox(
                label="Summary",
                lines=3
            )

            personalized_output = gr.Textbox(
                label="Personalized Message",
                lines=3
            )

            retail_output = gr.Textbox(
                label="Retail Insight",
                lines=3
            )

    submit_button.click(
        fn=gradio_analyze_review,
        inputs=review_input,
        outputs=[
            category_output,
            sentiment_output,
            urgency_output,
            summary_output,
            personalized_output,
            retail_output
        ]
    )

    clear_button.click(
        fn=lambda: ("", "", "", "", "", "", ""),
        inputs=None,
        outputs=[
            review_input,
            category_output,
            sentiment_output,
            urgency_output,
            summary_output,
            personalized_output,
            retail_output
        ]
    )

demo.launch(
    share=True,
    debug=True
)

try:
    demo.close()
except:
    pass

import json
import traceback
import gradio as gr

from review_analyzer import analyze_review
from google.colab import userdata


# ============================================================
# LOAD API KEY
# ============================================================

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY was not found in Colab Secrets."
    )


# ============================================================
# BACKEND FUNCTION
# ============================================================

def gradio_analyze_review(review_text):
    """
    Analyze one customer review and return the values required
    by the Gradio interface.
    """

    if not review_text or not review_text.strip():
        return (
            "⚠️ Please enter a customer review.",
            "",
            "",
            "",
            "",
            "",
            "",
            None
        )

    try:
        result = analyze_review(
            review_text.strip(),
            api_key=GEMINI_API_KEY
        )

        # Safeguard in case the function returns JSON text
        if isinstance(result, str):
            result = json.loads(result)

        if not isinstance(result, dict):
            raise TypeError(
                "The Gemini function did not return a dictionary."
            )

        category = result.get(
            "Category",
            "Not returned"
        )

        sentiment = result.get(
            "Sentiment",
            "Not returned"
        )

        urgency = result.get(
            "Urgency",
            "Not returned"
        )

        summary = result.get(
            "Summary",
            "Not returned"
        )

        personalized_message = result.get(
            "Personalized_Message",
            "Not returned"
        )

        retail_insight = result.get(
            "Retail_Insight",
            "Not returned"
        )

        # Human-in-the-loop status
        urgency_lower = str(urgency).lower()

        if urgency_lower == "high":
            status = (
                "🔴 **High Urgency — Immediate Human Review Required**"
            )

        elif urgency_lower == "medium":
            status = (
                "🟠 **Medium Urgency — Standard Support Follow-Up Required**"
            )

        else:
            status = (
                "🟢 **Low Urgency — No Immediate Escalation Required**"
            )

        return (
            status,
            category,
            sentiment,
            urgency,
            summary,
            personalized_message,
            retail_insight,
            result
        )

    except Exception as error:
        traceback.print_exc()

        error_message = (
            f"{type(error).__name__}: {error}"
        )

        return (
            f"❌ **Analysis failed:** {error_message}",
            "Error",
            "Error",
            "Error",
            error_message,
            "",
            "",
            {"error": error_message}
        )


# ============================================================
# CLEAR FUNCTION
# ============================================================

def clear_screen():
    return (
        "",
        "Enter a review and click Analyze Review.",
        "",
        "",
        "",
        "",
        "",
        "",
        None
    )


# ============================================================
# CUSTOM CSS
# ============================================================

custom_css = """
.gradio-container {
    max-width: 1250px !important;
    margin: auto !important;
}

#app-title {
    text-align: center;
    padding: 12px;
}

#app-subtitle {
    text-align: center;
    color: #666666;
    margin-bottom: 18px;
}

#analyze-button {
    font-weight: bold;
}

.status-banner {
    border-radius: 10px;
    padding: 8px;
}

.output-card textarea {
    min-height: 72px !important;
}

.business-output textarea {
    min-height: 130px !important;
}
"""


# ============================================================
# BUILD GRADIO SCREEN
# ============================================================

with gr.Blocks(
    title="ChicStyle Retail Feedback Intelligence"
) as demo:

    gr.Markdown(
        """
        # ChicStyle Retail Feedback Intelligence
        """,
        elem_id="app-title"
    )

    gr.Markdown(
        """
        Analyze customer feedback using Gemini and a structured
        Chain-of-Thought retail prompt.
        """,
        elem_id="app-subtitle"
    )

    status_output = gr.Markdown(
        "Enter a review and click **Analyze Review**.",
        elem_classes="status-banner"
    )

    with gr.Row():

        # ----------------------------------------------------
        # LEFT COLUMN — CUSTOMER INPUT
        # ----------------------------------------------------

        with gr.Column(scale=5):

            review_input = gr.Textbox(
                label="Customer Review",
                placeholder=(
                    "Paste an English, Spanish, Hindi, French, "
                    "or other customer review here..."
                ),
                lines=12,
                max_length=5000
            )

            with gr.Row():

                analyze_button = gr.Button(
                    "Analyze Review",
                    variant="primary",
                    elem_id="analyze-button"
                )

                clear_button = gr.Button(
                    "Clear"
                )

            gr.Examples(
                examples=[
                    [
                        "I love the design of this dress, but the "
                        "size is much smaller than expected and "
                        "the zipper broke after one use."
                    ],
                    [
                        "The shirt looks beautiful and fits well. "
                        "I would definitely recommend it."
                    ],
                    [
                        "Terrible fabric. I loved the shirt until "
                        "I washed it, but now it has lost its shape."
                    ],
                    [
                        "El vestido es muy bonito, pero la talla "
                        "es demasiado pequeña y la cremallera "
                        "se rompió."
                    ],
                    [
                        "कुर्ती का रंग अच्छा है, लेकिन कपड़े की "
                        "गुणवत्ता कमजोर है और डिलीवरी देर से हुई।"
                    ],
                    [
                        "La veste est élégante, mais la couleur "
                        "ne correspond pas à la photo et les "
                        "coutures semblent fragiles."
                    ]
                ],
                inputs=[review_input],
                label="Sample Reviews"
            )

        # ----------------------------------------------------
        # RIGHT COLUMN — CLASSIFICATION OUTPUTS
        # ----------------------------------------------------

        with gr.Column(scale=5):

            with gr.Row():

                category_output = gr.Textbox(
                    label="Category",
                    interactive=False,
                    elem_classes="output-card"
                )

                sentiment_output = gr.Textbox(
                    label="Sentiment",
                    interactive=False,
                    elem_classes="output-card"
                )

            urgency_output = gr.Textbox(
                label="Urgency",
                interactive=False,
                elem_classes="output-card"
            )

            summary_output = gr.Textbox(
                label="AI-Generated Summary",
                lines=5,
                interactive=False,
                elem_classes="output-card"
            )

    gr.Markdown("## Business-Ready Outputs")

    with gr.Row():

        personalized_output = gr.Textbox(
            label="Personalized Customer Response",
            lines=7,
            interactive=False,
            elem_classes="business-output"
        )

        retail_output = gr.Textbox(
            label="Retail Business Insight",
            lines=7,
            interactive=False,
            elem_classes="business-output"
        )

    with gr.Accordion(
        "Technical JSON Output",
        open=False
    ):

        json_output = gr.JSON(
            label="Structured Gemini Response"
        )

    gr.Markdown(
        """
        ---
        **Human-in-the-loop policy:** High-urgency cases must be reviewed
        by a customer-support specialist before a response is sent.

        *Powered by Google Gemini — ChicStyle Capstone Project*
        """
    )


    # ========================================================
    # EVENTS
    # ========================================================

    analysis_outputs = [
        status_output,
        category_output,
        sentiment_output,
        urgency_output,
        summary_output,
        personalized_output,
        retail_output,
        json_output
    ]

    analyze_button.click(
        fn=gradio_analyze_review,
        inputs=[review_input],
        outputs=analysis_outputs
    )

    review_input.submit(
        fn=gradio_analyze_review,
        inputs=[review_input],
        outputs=analysis_outputs
    )

    clear_button.click(
        fn=clear_screen,
        inputs=None,
        outputs=[
            review_input,
            status_output,
            category_output,
            sentiment_output,
            urgency_output,
            summary_output,
            personalized_output,
            retail_output,
            json_output
        ]
    )

demo.launch(
    share=True,
    debug=True,
    theme=gr.themes.Soft(),
    css=custom_css
)



# review_analyzer.py

import json
import requests

GEMINI_API_KEY = "YOUR_API_KEY"

def analyze_multilingual_review(review):
    ...
    return result